{"version":1,"defects":{"Warning":6,"Tests\\Unit\\RouterTest::it_registers_a_route":3,"Tests\\Unit\\RouterTest::test_that_there_are_no_routes_when_router_is_created":4,"Tests\\Unit\\RouterTest::test_that_it_throws_route_not_found_exception":4,"Tests\\Unit\\RouterTest::test_that_it_throws_route_not_found_exception with data set #0":4,"Tests\\Unit\\RouterTest::test_that_it_throws_route_not_found_exception with data set #1":4,"Tests\\Unit\\RouterTest::test_that_it_throws_route_not_found_exception with data set #2":3,"Tests\\Unit\\RouterTest::test_that_it_throws_route_not_found_exception with data set #3":3,"Tests\\Unit\\RouterTest::it_throws_route_not_found_exception with data set #2":3,"Tests\\Unit\\RouterTest::it_throws_route_not_found_exception with data set #3":3,"Error":4,"Tests\\Unit\\RouterTest::it_resolves_route_from_a_closure":4,"Tests\\Unit\\RouterTest::test_that_it_resolves_route_from_a_closure":4,"Tests\\Unit\\Services\\InvoiceServiceTest::it_process_invoice":3},"times":{"Warning":0.664,"Tests\\Unit\\RouterTest::it_registers_a_route":0.782,"Tests\\Unit\\RouterTest::test_that_it_registers_a_route":2.545,"Tests\\Unit\\RouterTest::test_that_it_reisters_a_post_route":0,"Tests\\Unit\\RouterTest::test_that_it_reisters_a_get_route":0,"Tests\\Unit\\RouterTest::test_that_there_are_no_routes_when_router_is_created":0.154,"Tests\\Unit\\RouterTest::test_that_it_throws_route_not_found_exception":1.135,"Tests\\Unit\\RouterTest::test_that_it_throws_route_not_found_exception with data set #0":0.919,"Tests\\Unit\\RouterTest::test_that_it_throws_route_not_found_exception with data set #1":0,"Tests\\Unit\\RouterTest::test_that_it_throws_route_not_found_exception with data set #2":0.174,"Tests\\Unit\\RouterTest::test_that_it_throws_route_not_found_exception with data set #3":0,"Tests\\Unit\\RouterTest::it_throws_route_not_found_exception with data set #0":0.379,"Tests\\Unit\\RouterTest::it_throws_route_not_found_exception with data set #1":0,"Tests\\Unit\\RouterTest::it_throws_route_not_found_exception with data set #2":0.001,"Tests\\Unit\\RouterTest::it_throws_route_not_found_exception with data set #3":0.001,"Error":0.193,"Tests\\Unit\\RouterTest::it_resolves_route_from_a_closure":0,"Tests\\Unit\\RouterTest::test_that_it_resolves_route_from_a_closure":0.06,"Tests\\Unit\\RouterTest::it_resolves_route":0,"Tests\\Unit\\Services\\InvoiceServiceTest::it_process_invoice":2.421,"Tests\\Unit\\Services\\InvoiceServiceTest::it_sends_receipt_email_when_invoice_is_processed":0.493}}